version: '3.8'

services:
  app:
    image: ${ECR_URL}/dreamketcher-dev-server:latest
    container_name: dreamketcher-dev-server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    command: [
      "redis-server",
      "--port", "6379",
      "--requirepass", "${REDIS_PASSWORD}",
      "--appendonly", "yes"
    ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: [
        "CMD",
        "redis-cli",
        "-a", "${REDIS_PASSWORD}",
        "ping"
      ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data: