server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_LOCAL_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  cookie:
    max-age: 12345678
    path: /
    same-site: none
    http-only: true
    secure: false

springdoc:
    swagger-ui:
      display-request-duration: true
    api-docs:
      path: /api-docs
      show-actuator: true

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    grant-type: authorization_code
    scope: email

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp: 12345678
  refresh-exp: 12345678
  expiration: 12345678

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false